[general]
live_config_reload = true
working_directory = "Repos"
import = ["~/.config/alacritty/themes/cyberdream.toml"]

[env]
TERM = "alacritty-direct"

[window]
decorations = "Buttonless"
opacity = 1.0
padding = { x = 18, y = 5 }

[scrolling]
history = 10000
multiplier = 3

[font]
size = 13.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Regular"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[colors]
draw_bold_text_with_bright_colors = true

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

